### ISSUE TITLE
Module 3 React + Redux Linking to wrong readme

### ISSUE THREAD

**Issue by alejo4373** [joinpursuit/Pursuit-Core-Web#110]
The Module 3 React + Redux [here in the main README](https://github.com/joinpursuit/Pursuit-Core-Web/blob/master/README.md#:~:text=Module%203%20-%20React%20+%20Redux)  is going to the wrong place. Not sure what it should point to since it seems that we won't separate/have react_1 & react_2 this time around.

**Comment by jabyess** [comment]
#99 and #97 merged in! thanks.

**Comment by jabyess** [comment]
Oops I meant #112 and #111
