### ISSUE TITLE
Two lessons revolving around APIs should be combined or reconciled

### ISSUE THREAD

**Issue by alejo4373** [joinpursuit/Pursuit-Core-Web#67]
I recently had some time and was reflecting on how we introduced APIs to fellows. Here are my thoughts: I think the lesson [api_intro](https://github.com/joinpursuit/Pursuit-Core-Web/tree/master/html_css_dom/api_intro) and [restful_apis](https://github.com/joinpursuit/Pursuit-Core-Web/tree/master/html_css_dom/restful_apis) should be revised and reconciled. I think **api_intro** should be about the HTTP protocol, HTTP methods and how to make network requests with Postman or curl to apis, . **restful_api** and CRUD should be left for when we are learning Express and how to create our own APIs. I think learning REST and CRUD in a front-end context is not as relevant. I also think the even loop on **api_intro** should be left for asynchronous JavaScript (AJAX). @benstone1 @coreyladovsky @CelineChole @xpectro93

**Comment by jabyess** [comment]
We're revamping a whole lot of this, and this is now a year old, so I'm gonna close this issue. Let us know if you want to get involved in some rewriting!
